### PR TITLE
Port and add samples for Media EffectAnimations 

### LINKED ISSUE #124: Improve Samples in Media

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR closes #124 by porting all existing samples for the Media package from the existing sample app. I've also added new samples for the EffectAnimations that didn't have them.

Opened as a draft PR as the `OpacityEffectAnimation` is not functional. Pending information from @Sergio0694.

Needs https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/102

### CODE REVIEW

**Comment by michael-hawker** [comment]
FYI @Arlodotexe 

```
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(10,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(11,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(12,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(13,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(14,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(15,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(16,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
         D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(17,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
```

**Comment by Arlodotexe** [comment]
> FYI @Arlodotexe
> 
> ```
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(10,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(11,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(12,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(13,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(14,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(15,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(16,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
>          D:\a\Windows\Windows\components\Media\samples\EffectAnimationsSampleOptions.xaml.cs(17,2): error CS0579: Duplicate 'ToolkitSampleOptionsPane' attribute [D:\a\Windows\Windows\components\Media\samples\Media.Samples.csproj]
> ```

Needs https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/102

**Comment by niels9001** [comment]
@Arlodotexe I'm gettting at runtime on WASDK:

`Attempt by method 'CommunityToolkit.WinUI.Media.Pipelines.PipelineBuilder..ctor(System.Func`1<System.Threading.Tasks.ValueTask`1<Microsoft.UI.Composition.CompositionBrush>>)' to access method 'CommunityToolkit.WinUI.Animations.GuidExtensions.ToUppercaseAsciiLetters(System.Guid ByRef)' failed.`

**Comment by niels9001** [comment]
@Arlodotexe tested via UWP sample app, works great! I'll push some (minor) design tweaks and then merge!

**Review by niels9001 — APPROVED** [review]

**Pull request merged**
