### PR TITLE
Fixed Codespace container build failure 

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR is an attempt to fix the Codespace build failures reported in #423.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Looks like this did the trick
image

**Comment by Arlodotexe** [comment]
Looks like there's a few issues with our vscode launch options.
image

I'm also seeing
```
/workspaces/Windows (codespace/fix-container-build) $ pwsh
bash: /usr/local/bin/pwsh: Permission denied

```
Might need to install powershell as part of the dockerfile.

**Comment by Arlodotexe** [comment]
Building the "All samples gallery" seems to work as expected now:
image

**Comment by Arlodotexe** [comment]
It's slow, but sample discovery and building also works again. 

image

**Review by michael-hawker — APPROVED** [review]

**Pull request merged**
