### PR TITLE
Porting RadialGauge

### PR DESCRIPTION
**Pull request by niels9001**
This PR ports over the `RadialGauge`:

- UWP/WASDK only (composition)
- Porting over `RadialGauge` from the existing toolkit
- Sample, docs and tests included.
- New modern look and feel
- New properties: `ScaleLength`, `ScaleTickCornerRadius`, `NeedleBorderBrush`, `NeedleBorderThickness`, `TickCornerRadius`, `TickPadding`

Before:
image

After:

Gauge

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Found a bug - setting the ScalePadding too high causes a crash.

https://github.com/CommunityToolkit/Windows/assets/9384894/860be0ac-70da-47ba-91d2-90763a9f4105

**Comment by XamlBrewer** [comment]
Definitely love the new position of the ticks, on the inside of the scale.

**Comment by XamlBrewer** [comment]
``The default value for **IsInteractive** (= reacting to touch and mouse events) was changed from _false_ to _true_. That's a good idea, but then you also need to register the _Tapped_ and _Manipulation*_ events in the _OnApplyTemplate_.

e.g. (not sure this way is the best practice though, but it works)
```
        OnInteractivityChanged(this, null);
        base.OnApplyTemplate();
```
Otherwise the gauge will not be interactive, even when set specifically:
`<controls:RadialGauge IsInteractive="True" />`

**Review by Arlodotexe — APPROVED** [review]

**Comment by Arlodotexe** [comment]
Before we merge this and publish to NuGet, I need to check that #43 won't be an issue here.

**Pull request merged**
