### PR TITLE
AdvancedCollectionView: Use generic arguments if possible to get type of elements in list

### PR DESCRIPTION
**Pull request by lhak**
Fixes https://github.com/CommunityToolkit/Windows/issues/78

### CODE REVIEW

**Comment by michael-hawker** [comment]
Thanks @lhak, can you add a unit test for this scenario so we can ensure we don't regress in the future?

**Comment by lhak** [comment]
I have added a test that reproduces the crash without the code changes

**Review by Arlodotexe — APPROVED** [review]
Tested locally that the issue exists and the code changes fix it. Looks good!

**Comment by Arlodotexe** [comment]
Carried over to https://github.com/CommunityToolkit/Windows/pull/182

**Pull request closed without merging**
