### PR TITLE
Update pointer for testing WebView2Loader removal

### PR DESCRIPTION
**Pull request by michael-hawker**
Tries to remove extraneous WebView2Loader that was included in WASDK 1.6. If this works we can report back to platform team for proper fix.

Required PR: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/216

Info in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/215

### CODE REVIEW

**Comment by michael-hawker** [comment]
Nope, this did not seemingly resolve the issue:

image

@Arlodotexe you want to confirm I put the flag in a good place in the tooling PR?

Btw, UWP packages look good now that we have the #490 / #500 regression fixed:

image

**Comment by Arlodotexe** [comment]
> @Arlodotexe you want to confirm I put the flag in a good place in the tooling PR?

Looks like it was put in a good place. If this is the correct property, I'm not sure why it'd be failing 🤔 
Would be good to dig through the binlog to see if the property was blocked by the condition or just didn't work.

**Comment by Arlodotexe** [comment]
Let's try Sergio's comment [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/215#issuecomment-2372494946)

**Comment by Arlodotexe** [comment]
@michael-hawker I've managed to fix the issue. It took a combination of updating WebView2 (as per @Sergio0694's suggestion) and removing both conditions around `WebView2NeverCopyLoaderDllToOutputDirectory`. Leaving either condition would result in broken packages again, but with both removed and webview2 updated:

image

This seems to have also resolved the issue with the extra `net8.0-windows10.0.22621.0` TFM being included alongside `net8.0-windows10.0.22621`.

**Comment by michael-hawker** [comment]
Looks good here! 🎉

image

Though now we have the hard/dependency inclusion of WebView2:

image

**Comment by Sergio0694** [comment]
> "Though now we have the hard/dependency inclusion of WebView2"

Mark that as `PrivateAssets="all"` for now to fix that. It's transitive anyway through WinAppSDK.

**Comment by michael-hawker** [comment]
> > "Though now we have the hard/dependency inclusion of WebView2"
> 
> Mark that as `PrivateAssets="all"` for now to fix that. It's transitive anyway through WinAppSDK.

FYI @Arlodotexe for https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/216

**Review by Arlodotexe — APPROVED** [review]

**Pull request merged**
