### PR TITLE
[GridSplitter] Fix #339: resize both items when they are fixed size to avoid the change overflowing to the irrelevant Star-sized item

### LINKED ISSUE #339: GridSplitter with '1*'-<sized>-<sized> columns does not resize as expected
### Describe the bug

`"CommunityToolkit.WinUI.Controls.Sizers" Version="8.0.240109"`

Consider a grid with 3 columns and 2 splitters as following:

```xaml
    <Grid
        VerticalAlignment="Stretch"
        BorderBrush="{ThemeResource SystemControlHighlightChromeHighBrush}"
        BorderThickness="0,0,1,1">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="300*" MinWidth="100" />
            <ColumnDefinition Width="Auto" MinWidth="6" />
            <ColumnDefinition Width="300" MinWidth="32" />
            <ColumnDefinition Width="Auto" MinWidth="6" />
            <ColumnDefinition Width="300" MinWidth="32" />
        </Grid.ColumnDefinitions>

        <Border
            Grid.Row="0"
            Grid.Column="0"
            Background="MidnightBlue">
            <TextBlock Text="This text is in a column with 1* Width - This is what causes the second splitter not to work." TextWrapping="Wrap" />
        </Border>
        <Border Grid.Row="0" Grid.Column="2">
            <TextBlock Text="This column resizes properly, and if it's the only one after the 1* column, it also resizes properly." TextWrapping="Wrap" />
        </Border>
        <Border
            Grid.Row="0"
            Grid.Column="4"
            Background="DarkRed">
            <TextBlock Text="This text Is not resizing - Grid.Column.Width = 300 - ResizeBehavior=PreviousAndNext" TextWrapping="Wrap" />
        </Border>

        <!--  Column Grid Splitter  -->
        <controls:GridSplitter
            Grid.Column="1"
            Width="16"
            ResizeBehavior="PreviousAndNext"
            ResizeDirection="Auto" />

        <!--  Row Grid Splitter  -->
        <controls:GridSplitter
            Grid.Column="3"
            Width="16"
            ResizeBehavior="PreviousAndNext"
            ResizeDirection="Auto" />
    </Grid>
```

Splitter at Column 1 works fine, but splitter at Column 3 does not resize Column 4 as expected.

### Steps to reproduce

Run the attached sample.

[GridSplitterBug.zip](https://github.com/CommunityToolkit/Windows/files/14335853/GridSplitterBug.zip)

### Expected behavior

Given that the splitter is configured to resize PreviousAndNext, it is supposed to resize both columns.

### Screenshots

https://github.com/CommunityToolkit/Windows/assets/457645/f54d0e95-051a-44c7-a36e-60b2df112f94

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [X] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

Any version of windows 

### App minimum and target SDK version

- [X] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

2022

### Visual Studio Build Number

latest

### Device form factor

Desktop

### Additional context

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Sizers" Version="8.0.240109" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.230913002" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.2428" />
	</ItemGroup>

### Help us help you

Yes, I'd like to be assigned to work on this item.

### PR DESCRIPTION
**Pull request by abdes**
## Fixes

Fixes #339 

Please see #339 for a detailed description of the problem with video of the interaction.

- Formatted the GridSplitter experiment XAML code with XAMLStyler to avoid unnecessary diffs in the history. Please note that this is theoretically unnecessary, but it should be done anyway given that the project requires XAMLStyler style to be enforced.
- Augmented the GridSplitter sample to add one more column and set the last 2 columns to fixed size to demonstrate the issue before the fix and the resolution after the fix.
- Fixed the issue by making the GridSplitter resize both current and sibling when they are both fixed size.
- Verified that the new behavior honors the minimum size constraint.

## PR Type

What kind of change does this PR introduce?

Bugfix
Code style update (formatting)

Sample app changes

## What is the current behavior?

Please see #339 for a detailed description of the problem with video of the interaction.

## What is the new behavior?

https://github.com/CommunityToolkit/Windows/assets/457645/67aa5a60-5e85-493e-82b0-915a4c8da78c

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [X] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [X] Based off latest main branch of toolkit
- [ ] Tested code with current supported SDKs
- [ ] New component
  - [ ] Documentation has been added
  - [ ] Sample in sample app has been added
  - [ ] Analyzers are passing for documentation and samples
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [X] Tests for the changes have been added (if applicable)
- [ ] Header has been added to all new source files
- [X] Contains **NO** breaking changes

### CODE REVIEW

**Comment by abdes** [comment]
@dotnet-policy-service agree

**Comment by michael-hawker** [comment]
@abdes it appears you applied different XAML Styler settings than the for the file we have in the repo, ensure your plugin is configured to look upwards in the folder structure for settings files.

I also don't think this behavior is correct. If the limit has been reached for the size a column should grow, no more movement should occur. Here we see the 1 & 2 columns being affected by the changes to the 3 & 4 now, i.e. the third column growing more as you continue to drag to the right and pushing the other two out of the way.

Once the 4th column is the smallest, it should no longer update anything else.

There is ambiguity in if the last column should be able to go beyond the size of the grid. I believe in WPF, it would extend the size of the grid itself to grow beyond the original bounds.

**Comment by abdes** [comment]
Got it.

- Reverted the changes on styling. Just used the PowerShell script. Could not find how to make the VS Extension auto-find the XAMLStyler config.

- For the resizing, now it checks the constraints (for both the current and the sibling) before allowing the resize to proceed. Previously, the check was only done for the row/column being changed. In fact it should be done for both because if any of the two impacted rows/columns cannot be resized then the other one should not be resized as well.

**Comment by abdes** [comment]
Can we get a reviewer to move this forward please?
I've attached videos, met all requirements and am ready to make any additional modifications needed.

**Comment by abdes** [comment]
@Arlodotexe 
Please approve the workflow...

**Review by Arlodotexe — APPROVED** [review]
Tested locally under Uwp, Wasdk and Wasm. Code looks good and it does fix the issue. Let's get this merged! 🎉

**Pull request merged**
