### PR TITLE
Fixed codespaces not cloning submodule automatically

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR fixes an issue where codespaces weren't automatically cloning the required submodule when first started up.

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Needs #145

**Comment by michael-hawker** [comment]
@Arlodotexe once this is good we should be able to test on Codespaces again, eh? Wonder if that'll help diagnose what's wrong in #138... I'm a bit confused by this one.

**Comment by Arlodotexe** [comment]
```
The active test run was aborted. Reason: Unable to communicate with test host process.
Terminating app with process ID '6328'.
Results File: D:\a\Windows\Windows\TestResults\WinAppSdk.trx

Test Run Aborted with error System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
Total tests: Unknown
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
     Passed: 270
   --- End of inner exception stack trace ---
    Skipped: 2
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
 Total time: 39.5070 Seconds
Error: Process completed with exit code 1.
```

Hmmm

**Comment by michael-hawker** [comment]
@Arlodotexe been seeing that issue a lot on both pipelines, not sure what's going on. Every now and then restarting doesn't work. Assuming something updated on the environment again? No idea why it's failing though.

**Pull request merged**
