### PR TITLE
Add new Horizontal ContentAlignment for SettingsCard

### LINKED ISSUE #577: Settings content can’t horizontally align in SettingsCard
### Describe the bug

I’m trying to add an additional image in the SettingsCard. It’s supposed to stretch the available area in SettingsCard but only align to the right side. Many available areas will be lost in the middle of SettingsCard

### Steps to reproduce

```text
1. Open any SettingsCard
2. Add an additional content such as image in the SettingsCard
```

### Expected behavior

Settings content fully stretch the available area in SettingsCard

### Screenshots

Image

### Code Platform

- [x] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [x] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

_No response_

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [x] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

2022

### Visual Studio Build Number

_No response_

### Device form factor

Desktop

### Additional context

_No response_

### Help us help you

Yes, I'd like to be assigned to work on this item.

### PR DESCRIPTION
**Pull request by ProJend**
## PR Type

What kind of change does this PR introduce?
Other: Feature added

## What is the current behavior?
屏幕截图 2024-12-01 210755

## What is the new behavior?
屏幕截图 2024-12-01 210754

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [x] Tested code with current supported SDKs
- [ ] New component
  - [ ] Documentation has been added
  - [ ] Sample in sample app has been added
  - [ ] Analyzers are passing for documentation and samples
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (if applicable)
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by ProJend** [comment]
> @ProJend please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by niels9001** [comment]
@ProJend Just to be sure, have you tried this change with the different SettingsCard samples in the Gallery app?

There are a couple of alignment settings you could set that might already achieve the same result (see the Gallery samples)?

**Comment by ProJend** [comment]
@niels9001 Not yet. This is my first time to request pull. It should take more time to test more samples.

And the couple of alignment settings is not working for settings content. I think it's better to use `VisualState` to stretch automatically both settings header and settings content in SettingsCard

**Comment by ProJend** [comment]
@niels9001 I have reverted back to default style. It should repair the breaking wrapping layout. 

Unfortunately I don't know how to test them in the gallery, so not sure whether `ContentAlignment="Horizontal"` and `SettingsCardHeaderPanelMaxWidth` both work properly.

**Pull request closed without merging**
