### PR TITLE
Fixes issues with the build script in detecting dump files to upload and analyze

### PR DESCRIPTION
**Pull request by michael-hawker**
#170 failed on `main` here: https://github.com/CommunityToolkit/Windows/actions/runs/5828716207/job/15806953245

image

But the dump detection, upload, and auto-analysis didn't run.

I missed that the plugin (dorny/paths-filter) I picked doesn't work on untracked files, only git files. So using [GitHub Action output](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-setting-an-output-parameter) to search for a dump file and use that for analysis.

Will see if this build fails at least once for a test... (the rare time you want something to fail)...

Fixes https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/7 in https://github.com/CommunityToolkit/Windows/pull/174/commits/c18dc07bebc98b7150513d2537b0662f32c2f6e0

### CODE REVIEW

**Comment by michael-hawker** [comment]
Was using linux command, but the default [Windows shell is PowerShell](https://github.blog/changelog/2019-10-17-github-actions-default-shell-on-windows-runners-is-changing-to-powershell/), so adjusted command, should be good now.

Also VS Code kept modifying the config file due to the new dotnet environment they shipped, so made change here so it stops modifying it locally all the time.

**Comment by michael-hawker** [comment]
Ok, didn't realize PowerShell would throw an error and stop things inline like that, added `SilentlyContinue` to the command, so now should be blank as expected if no files found.

**Comment by michael-hawker** [comment]
Added always flag for detecting the dump file.

**Comment by michael-hawker** [comment]
Still not doing what I expect with the detection... outputting some tests

Removed the vs code config stuff, something happened with an infinite loop for me locally suddenly with the new C# extension (conflict between need for msbuild as winappsdk vs. it trying to use dotnet or something...) We'll have to look into that later for #101

**Comment by michael-hawker** [comment]
Think I've got the build stuff sorted now with the auto-dump analysis (though doesn't seem as helpful in these test scenarios without more commands), though adding /Blame to the test runner does provide nicer output of the crash.

Tried ignoring a few tests that pop-up in the logs, but really think this is a memory constriction type issue.

**Comment by michael-hawker** [comment]
Rebased on top of #173 in order to get preview feed packages so I can check NuGet icon whilst I'm doing builds.

**Comment by michael-hawker** [comment]
@Arlodotexe do you want us to merge this into your .NET 7 branch as it should be more stable with the few disabled tests hopefully (or at least better report ones that are still problematic)?

**Comment by Arlodotexe** [comment]
If the CI keeps failing on #117, I will do that. Otherwise I plan on closing #117 and then closing this.

**Comment by michael-hawker** [comment]
Hmm, filename change for casing didn't make a difference. The `iconUrl` is showing up in the manifest though, so it's something specific to do with `PackageIcon`... we're doing everything according to the docs, so not sure what's wrong here and why that isn't showing up in the package metadata... Going to try updating the NuGet Pack lib and see what happens. Think SourceLink is changing too, but we can investigate that later too, maybe that's a .NET 8 thing...

**Comment by michael-hawker** [comment]
Alright, rebased back on top of main so we can merge ahead of #173 if needed.

**Comment by niels9001** [comment]
@michael-hawker Nit: Nuget recommends a 128x128px icon vs. the 256 we use now? But I'll PR and update that so this can go through!

**Review by niels9001 — APPROVED** [review]

**Pull request merged**
