### PR TITLE
Exclude uap in WinUI package, wasdk in UWP package

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR fixes an issue with our CI where the built UWP and WinUI packages included "All" multitargets. 

Including both doesn't cause issues in UWP or WinUI projects normally as the correct TFM is picked up. However, in certain scenarios uap may be picked up when the winappsdk TFMs were intended, such as in the packaging project for applications using the Windows Application Packaging setup. 

Closes https://github.com/CommunityToolkit/Windows/issues/490#issuecomment-2332805012

### CODE REVIEW

**Comment by michael-hawker** [comment]
Ah, I see, our old setup used to do this at one point, as we had discussed whether packages should contain the other framework for Windows developers, and then hit an issue with that scenario, so we removed it at one point. That was this issue here: https://github.com/CommunityToolkit/Windows/issues/220 (I added this comment to this new issue, we can classify this as a regression at least.)

**Comment by Arlodotexe** [comment]
That's right @michael-hawker. In the local solution, we allow `all` to include both `uwp` and `wasdk` regardless of the WinUI major version requested, to allow them to both load in our solution. It's not behavior we want from our CI due to the way other solution setups might select the wrong TFM.

**Comment by Arlodotexe** [comment]
Checking from the PR feed, it looks like this didn't change the TFMs produced 🤔 

Need to investigate why. It's either a variable not being passed into the CI step, or the value is being passed and it's an issue with the underlying script.

**Comment by Arlodotexe** [comment]
@michael-hawker Looks like that did the trick, we should be good to go!

 image

**Comment by Arlodotexe** [comment]
Curious why UWP is missing symbols though 🤔 

Should we do a follow-up patch PR or try fixing it here? Seems priority to ship this patch for Windows Application Packaging project users.

**Comment by michael-hawker** [comment]
Hmm, I see the UWP ones from the main latest feed missing it too:

image

Though our released 8.1.240821 seems fine for both on our MainLatest feed.

We should try and understand what's happened here. Looks like it started in the first build of 8.2 (above)

Ugh, looks like our 1148 with just the version got stuck 😡 https://github.com/CommunityToolkit/Windows/actions/runs/10514400206/job/29135997093 - going to re-kick that if I can to see what that looks like for comparison as that should just be the version number change.

1153 corresponds from this PR here: https://github.com/CommunityToolkit/Windows/pull/457 with our update to WASDK 1.6, so somehow the flags are getting changed because of that.

----

Our goal is to patch this into 8.1 though, so this should be unaffected and something we can do still.

But, I thought you were planning to branch this PR from main before we switched to 8.2? Why are we getting the 8.2 version numbers/changes?

Our plan should be either:

1. Fix forward and backport for the hotfix
  a. Ensure this is rebased on `main` and integrate as-is
  b. File a new ticket for the compiler symbols/flags, etc... to resolve for 8.2
  c. locally, create a new `rel/8.1.YYMMDD` branch from the `rel/8.1.240821` branch and cherry-pick this specific build script change commit
  d. push that branch, validate the package in ADO feed, and push the hotfix release to NuGet
2. Backfix and re-integrate
  a. locally create a `rel/8.1.YYMMDD` branch and rebase this commit on top of `rel/8.1.YYMMDD` in that branch
  b. push that branch, validate the package in ADO feed, and push the hotfix release to NuGet
  c. merge that rel branch back into main

@azchohfi we haven't done a hotfix in our new branching model like this, so would appreciate any insights, recommendations, or feedback you have with these approaches.

**Comment by Arlodotexe** [comment]
Good catch @michael-hawker, it should still be 8.1, not 8.2. I branched off of b99aa1f018ce178d03475bf76b597c1bb4b1e1b7, which was the commit just before we bumped our version to 8.2 4b6c77a680814733a46bcf80ec840228115c944d, so that's a good question 🤔

**Comment by Arlodotexe** [comment]
Looks like the CI is checking out f0544474d2f9bd86ea8ced7e9c2fb9f724d936b6 ([see run](https://github.com/CommunityToolkit/Windows/actions/runs/10780636631/job/29898975626?pr=500#step:4:57)), which is a merge commit of 952b239d854bd9cfe46aa7cf997345ab19453dfc (the commit we intended to build) into 3e6703b0c04b636d47b2fa53005d1c05062cdee7 (latest from main). 

The commit checked out by Actions does not match my local branch, which still has this branch and `main` well separated:

image

If we [browse the repo at the current branch](https://github.com/CommunityToolkit/Windows/blob/fix/nupkg/uap-in-winui-package/Directory.Build.props#L4) `fix/nupkg/uap-in-winui-package`, we can see that `Directory.Build.props` is still set to 8.1. 

Using GitHub's compare tool https://github.com/CommunityToolkit/Windows/compare/fix/nupkg/uap-in-winui-package...main, we can see the 8.2 bump hasn't been merged into this branch yet. 
image

GitHub Actions is checking out with a detached merge between this branch and `main`, adding commits intended for 8.2 and not 8.1.

**Comment by Arlodotexe** [comment]
Found an open issue: https://github.com/actions/checkout/issues/1359

**Comment by Arlodotexe** [comment]
Looks like this setup:
```
      - name: Checkout Repository
        uses: actions/checkout@v4	        uses: actions/checkout@v4
        with:	        with:
          submodules: recursive	          submodules: recursive
          ref: ${{ github.ref }}
```
Is checking out 8fc117d, which is a different hash but has the same problem as before.

**Comment by Arlodotexe** [comment]
@michael-hawker I've created a `pre/rel/8.1.240821` branch from our existing `rel/8.1.240821`, and changed this PR base to that branch. Hopefully should resolve the merge issue we're seeing with Actions during checkout

**Comment by Arlodotexe** [comment]
Looks like some checks aren't appearing in CI now, closing and re-opening to fix.

**Comment by Arlodotexe** [comment]
Seems like our `build.yml` preferences only kicked in when I pushed, _after_ changing the base branch from `main` to [`pre/rel/8.1.240911`](https://github.com/CommunityToolkit/Windows/tree/pre/rel/8.1.240911). 

@michael-hawker CI ran once checked out from the commit we want but won't run again because of our `build.yml` preferences. Thoughts?

https://github.com/CommunityToolkit/Windows/blob/3e6703b0c04b636d47b2fa53005d1c05062cdee7/.github/workflows/build.yml#L13

**Comment by Arlodotexe** [comment]
Checks still aren't running, maybe c859b6e44dd75062b95c24845831962d0aee6cd3 needs to be in the target branch? 🤔

**Comment by Arlodotexe** [comment]
That didn't help... Need to figure out where GitHub is getting the policy from for this.

**Comment by michael-hawker** [comment]
> Checks still aren't running, maybe [c859b6e](https://github.com/CommunityToolkit/Windows/commit/c859b6e44dd75062b95c24845831962d0aee6cd3) needs to be in the target branch? 🤔

I think you need it duplicated in the push trigger as well? Not 100% sure, but that's what I'd try next.

**Comment by Arlodotexe** [comment]
We merged both #504 and #505 into `main`, the same commits pushed to [`dev/rel/8.1.240912`](https://github.com/CommunityToolkit/Windows/tree/dev/rel/8.1.240912) and [`fix/nupkg/uap-in-winui-package`](https://github.com/CommunityToolkit/Windows/tree/fix/nupkg/uap-in-winui-package) (this branch). 

This should have allowed CI checks to run for merging into a `dev/*` branch instead of just `main`, but that doesn't seem to have worked.

**Comment by Arlodotexe** [comment]
@michael-hawker For now, I've manually kicked off [CommunityToolkit/Windows/actions/runs/10853702741](https://github.com/CommunityToolkit/Windows/actions/runs/10853702741). It's still not clear why checks aren't running here.

**Review by michael-hawker — APPROVED** [review]

**Pull request merged**
