### PR TITLE
Update tooling submodule for rebrand changes

### PR DESCRIPTION
**Pull request by michael-hawker**
Test PR for changes from https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/110

This may require other changes to props files here, but wanted to get it started so we wouldn't forget.

### CODE REVIEW

**Comment by michael-hawker** [comment]
@niels9001 we need to define the props here https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/110/files#diff-59b3c86cb2022d95986b7d43ceebaad7532a5d64bb9634310f0d84f6d4360a4eR43-R78 in the build config, eh?

**Comment by michael-hawker** [comment]
This is ready to go in after #194

**Comment by michael-hawker** [comment]
Rebased on latest main of this repo and the tooling for the submodule update, should be all good.

**Review by Arlodotexe — APPROVED** [review]
Tested locally, everything looks good!

**Pull request merged**
