### PR TITLE
Fix: AdvancedCollection inserts at wrong position when adding to end of source collection

### LINKED ISSUE #307: AdvancedCollection inserts element at wrong position when the element is added at the end of the source collection
### Describe the bug

This means if the new item is at the end of `source`

https://github.com/CommunityToolkit/Windows/blob/8e4bd7a213210feff42ade340a8be6624e9f5c64/components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.cs#L699-L702

Then we insert it into the penultimate position of the view. It is wired.

https://github.com/CommunityToolkit/Windows/blob/8e4bd7a213210feff42ade340a8be6624e9f5c64/components/Collections/src/AdvancedCollectionView/AdvancedCollectionView.cs#L725-L725

Isn't it meant to be inserted into the last position?

### Steps to reproduce

```text
None.
```

### Expected behavior

None.

### Screenshots

_No response_

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

_No response_

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

_No response_

### Visual Studio Build Number

_No response_

### Device form factor

_No response_

### Additional context

_No response_

### Help us help you

Yes, I'd like to be assigned to work on this item.

### PR DESCRIPTION
**Pull request by Poker-sang**
## Fixes

closes #307 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the new behavior?

The new item is now added to the end of the collection.

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [x] Tested code with current supported SDKs
- [ ] New component
  - [ ] Documentation has been added
  - [ ] Sample in sample app has been added
  - [ ] Analyzers are passing for documentation and samples
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (if applicable)
- [ ] Header has been added to all new source files
- [ ] Contains **NO** breaking changes

### CODE REVIEW

**Comment by Arlodotexe** [comment]
Quickly testing [here](https://dotnetfiddle.net/XJt39U), `list.Insert(list.Count - 1, newItem);` would insert into the second-to-last position rather than the first.

There's [no exceptions thrown](https://dotnetfiddle.net/dOkSXe) when you `list.Insert(list.Count, newItem);` rather than calling `list.Add()`. 

Since the intention is to keep the `List<object> _view` field in sync with the `IList _source` field, this change should fix an issue where items aren't added to the end of the AdvancedCollectionView when the underlying source collection is `ObservableCollection` and updated.

I'll set up a quick minimal repro so we can observe the issue and make sure this fix does what we want.

**Comment by abdes** [comment]
The impact of this PR is really minimal, and it fixes an obvious bug. Please review and move forward.

**Comment by abdes** [comment]
@Arlodotexe what's the additional work needed here? Can we get this merged or can we get a review comment for what else needs to be done so we can get it done? This is a pretty bad bug as it breaks an important assumption of the AdvancedCollection staying in sync with the original collection.

**Comment by Lightczx** [comment]
Honestly, I already copied the source code into my project,
waiting for the package to get updated might take us several mouths.

**Comment by abdes** [comment]
> Honestly, I already copied the source code into my project, and even refactored it into generic compat waiting for the package to get updated might take us several mouths.

Care to share the link to your improved version @Lightczx ?

**Comment by Poker-sang** [comment]
> Honestly, I already copied the source code into my project, and even refactored it into generic compat waiting for the package to get updated might take us several mouths.

Me too. But the new controls `ItemsView`&`ItemsRepeater` which can replace `ListView`&`GridView`, do not support `ICollectionView`. So, I dropped `ICollectionView` and reimplemented it based on `ObservableCollection<T>`.

**Comment by abdes** [comment]
Well, if that's the new model of Microsoft OpenSource projects, then so be it. We just copy the code, fix it an use it... Long live the MIT License. 

Any of the maintainers care to comment on why Pull Requests submitted, even after thorough explanation, testing and due diligence by the submitter, get stuck at "Review Required" with no feedback?

**Comment by Arlodotexe** [comment]
> Any of the maintainers care to comment on why Pull Requests submitted, even after thorough explanation, testing and due diligence by the submitter, get stuck at "Review Required" with no feedback?

We're still putting together the 8.1 update and in addition to features and bug fixes, we've been ironing out various tooling issues that have been cropping up. Adding `net8-windows` support to Wasdk caused significantly more trouble than we anticipated, PowerShell got updated underneath us and broke CI, the new ColorPicker package is behaving strangely when consumed, the list goes on.

You can follow along and see where we're at in the [current iteration](https://github.com/orgs/CommunityToolkit/projects/7/views/2) of our project board for 8.x.

We just recently closed off some of the larger issues we were having (again, see the .net8 prs [1](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/165) [2](https://github.com/CommunityToolkit/Windows/pull/328)), so I plan to start closing off the smaller bugfix PRs now (like this one).

Thanks for your patience 🙂

**Comment by abdes** [comment]
Thank you for the update.

**Comment by Arlodotexe** [comment]
@Poker-sang Good news! I've fleshed out our unit tests for this control more and was able to reproduce the issue described. I can confirm that the changes you've made fixes the broken test case, so we're good to close once CI passes 🚀

**Review by Arlodotexe — APPROVED** [review]

**Pull request merged**
