### PR TITLE
Update Microsoft.WindowsAppSDK to 1.6-preview2

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR updates our tooling to use Microsoft.WindowsAppSDK 1.6-preview2 and removes prior workarounds only needed for preview1.

Prerequisite PR: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/208

### CODE REVIEW

**Comment by michael-hawker** [comment]
@Arlodotexe is there anything that's blocking us from merging the preview2 updates?

**Comment by Arlodotexe** [comment]
> @Arlodotexe is there anything that's blocking us from merging the preview2 updates?

Nothing blocking us from merging, CI seems to be all green and it's working well deployed locally. 

Was hoping to use this PR to work through the additional `CsWinRTAotWarningLevel` analyzer warnings suggested by Sergio [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/195#discussion_r1722185832), in the last PR.

**Comment by Arlodotexe** [comment]
> > @Arlodotexe is there anything that's blocking us from merging the preview2 updates?
> 
> Nothing blocking us from merging, CI seems to be all green and it's working well deployed locally.
> 
> Was hoping to use this PR to enable and work through the additional `CsWinRTAotWarningLevel` analyzer warnings suggested by Sergio [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/195#discussion_r1722185832), in the last PR.

With 1.6 stable out now, we'll do this in a separate PR to keep things moving.

**Review by michael-hawker — APPROVED** [review]

**Comment by michael-hawker** [comment]
Approved to unblock you once the tooling submodule is updated

**Pull request merged**
