### PR TITLE
fix: Uno Platform - Avoid square border around `RangeSelector` `Thumbs`

### LINKED ISSUE #386: [`RangeSelector`] on WASM draws squares around track controls
### Describe the bug

image

### Steps to reproduce

```text
Create a blank Uno app
Add a `RangeSelector` to the main page
Launch WASM head
```

### Expected behavior

No square borders around track controls

### Screenshots

_No response_

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [X] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### Other Windows Build number

_No response_

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Other SDK version

_No response_

### Visual Studio Version

2022

### Visual Studio Build Number

_No response_

### Device form factor

_No response_

### Additional context

_No response_

### Help us help you

Yes, but only if others can assist.

### PR DESCRIPTION
**Pull request by MartinZikmund**
## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

There is a square around Thumbs

## What is the new behavior?

No square around thumbs, This workaround is for https://github.com/unoplatform/uno/issues/6457

## PR Checklist

Please check if your PR fulfills the following requirements: 

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [ ] Tested code with current supported SDKs
- [ ] New component
  - [ ] Documentation has been added
  - [ ] Sample in sample app has been added
  - [ ] Analyzers are passing for documentation and samples
  - [ ] Icon has been created (if new sample) following the [Thumbnail Style Guide and templates](https://github.com/CommunityToolkit/WindowsCommunityToolkit-design-assets)
- [ ] Tests for the changes have been added (if applicable)
- [ ] Header has been added to all new source files
- [x] Contains **NO** breaking changes

### CODE REVIEW

**Comment by michael-hawker** [comment]
Thanks @MartinZikmund, guess we don't expect the Uno issue to get resolved in the near-term? I saw you applied a similar fix to the ColorPicker control for Uno, don't think our revamped ColorPicker in the toolkit we added was effected by this, eh @Arlodotexe?

**Comment by MartinZikmund** [comment]
@michael-hawker indeed, especially on WASM it is pretty tricky... `ColorPicker` was not affected as it does not use the linear gradient

**Comment by Arlodotexe** [comment]
Thanks @MartinZikmund, looks like there's an error here:
```
2024-04-24T02:02:26.1277663Z        "C:\a\Windows\Windows\components\RangeSelector\src\CommunityToolkit.WinUI.Controls.RangeSelector.csproj" (default target) (34:39) ->
2024-04-24T02:02:26.1278246Z        "C:\a\Windows\Windows\components\RangeSelector\src\CommunityToolkit.WinUI.Controls.RangeSelector.csproj" (Build target) (34:45) ->
2024-04-24T02:02:26.1278408Z        (MarkupCompilePass1 target) -> 
2024-04-24T02:02:26.1279940Z          C:\a\Windows\Windows\components\RangeSelector\src\RangeSelector.xaml(33,34): XamlCompiler error WMC0001: Unknown type 'Setter' in XML namespace 'http://uno.ui/not_win' [C:\a\Windows\Windows\components\RangeSelector\src\CommunityToolkit.WinUI.Controls.RangeSelector.csproj::TargetFramework=uap10.0.17763]
```

**Comment by MartinZikmund** [comment]
@Arlodotexe forgot the mc:Ignorable, please retry, should help

**Comment by MartinZikmund** [comment]
@Arlodotexe and once more for styling 😅

**Comment by Arlodotexe** [comment]
> @Arlodotexe and once more for styling, hopefully will work out this time 😅
> 
> Wanted to verify with the sample app, but getting:
> 
> ```
> 1>D:\Work\CommunityToolkitWindows\tooling\ProjectHeads\AllComponents\Wasm\obj\Debug\net7.0\CommunityToolkit.Tooling.SampleGen\CommunityToolkit.Tooling.SampleGen.ToolkitSampleMetadataGenerator\ToolkitSampleRegistry.g.cs(38,781,38,796): error CS1744: Named argument 'showAsNumberBox' specifies a parameter for which a positional argument has already been given
> 1>D:\Work\CommunityToolkitWindows\tooling\ProjectHeads\AllComponents\Wasm\obj\Debug\net7.0\CommunityToolkit.Tooling.SampleGen\CommunityToolkit.Tooling.SampleGen.ToolkitSampleMetadataGenerator\ToolkitSampleRegistry.g.cs(42,569,42,572): error CS8323: Named argument 'min' is used out-of-position but is followed by an unnamed argument
> ```

That's odd, it looks like our SampleGen tooling is generating invalid metadata for a `[ToolkitSampleNumericOption(...)]` somewhere, likely for the RangeSelector. It may be a transient error, if CI doesn't pass I can give a hand.

**Comment by MartinZikmund** [comment]
@Arlodotexe the error now seems unrelated, or not?

**Comment by Arlodotexe** [comment]
> @Arlodotexe the error now seems unrelated, or not?

Fixed this CI error recently in https://github.com/CommunityToolkit/Windows/pull/411, should be good now.

**Comment by MartinZikmund** [comment]
@Arlodotexe seems it helped 👍👍

**Comment by Arlodotexe** [comment]
> @Arlodotexe seems it helped 👍👍

Great! Tested on WebAssembly, looks like this did the trick. Thanks @MartinZikmund!

image

**Review by Arlodotexe — APPROVED** [review]

**Pull request merged**
