### PR TITLE
Update Uno version, Uno TFMs to .NET 8

### PR DESCRIPTION
**Pull request by Arlodotexe**
This PR:
- Updates our Uno packages to the latest stable version
- Updates the TFMs that Uno runs on from net7.0 to net8.0
- Fixes any issues that arise from the move to net8.0

Prerequisite PR https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/191

### CODE REVIEW

**Comment by Arlodotexe** [comment]
@michael-hawker This is ready to go when the prerequisite tooling PR is merged.

**Comment by michael-hawker** [comment]
Looks like there's some sort of Android error in the build:

```
error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Ref.33' was not present in workload manifests. [C:\a\Windows\Windows\components\Triggers\samples\Triggers.Samples.csproj::TargetFramework=net8.0-android33.0]
```

**Comment by Arlodotexe** [comment]
The latest error from the CI:
```
2024-06-03T18:06:49.9856825Z        "C:\a\Windows\Windows\CommunityToolkit.AllComponents.sln" (default target) (1:2) ->
2024-06-03T18:06:49.9857792Z        "C:\a\Windows\Windows\tooling\ProjectHeads\AllComponents\Wasm\CommunityToolkit.App.Wasm.csproj" (default target) (57:6) ->
2024-06-03T18:06:49.9858540Z        (CoreCompile target) -> 
2024-06-03T18:06:49.9859654Z          C:\a\Windows\Windows\tooling\CommunityToolkit.App.Shared\App.xaml.cs(17,60): error CS8601: Possible null reference assignment. [C:\a\Windows\Windows\tooling\ProjectHeads\AllComponents\Wasm\CommunityToolkit.App.Wasm.csproj]
2024-06-03T18:06:49.9860684Z 
2024-06-03T18:06:49.9860762Z     22 Warning(s)
2024-06-03T18:06:49.9860981Z     1 Error(s)
```

**Comment by michael-hawker** [comment]
Hmm, test failing now:

```
Failed Test_RichSuggestBox_AddTokens (@Token1,@Token2,@Token3) [86 ms]
  Error Message:
   Assert.IsTrue failed. SuggestionChosen was not invoked.
  Stack Trace:
     at RichSuggestBoxExperiment.Tests.Test_RichSuggestBox.TestAddTokenAsync(RichSuggestBox rsb, String tokenText) in C:\a\Windows\Windows\components\RichSuggestBox\tests\Test_RichSuggestBox.cs:line 354
   at RichSuggestBoxExperiment.Tests.Test_RichSuggestBox.<>c__DisplayClass0_0.<<Test_RichSuggestBox_AddTokens>b__0>d.MoveNext() in C:\a\Windows\Windows\components\RichSuggestBox\tests\Test_RichSuggestBox.cs:line 33
--- End of stack trace from previous location ---
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass3_0.<<EnqueueAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at RichSuggestBoxExperiment.Tests.Test_RichSuggestBox.Test_RichSuggestBox_AddTokens(String tokenText1, String tokenText2, String tokenText3) in C:\a\Windows\Windows\components\RichSuggestBox\tests\Test_RichSuggestBox.cs:line 26
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

**Comment by Arlodotexe** [comment]
@michael-hawker Possibly transient / related to https://github.com/CommunityToolkit/Windows/issues/347. I'll rerun.

**Comment by Arlodotexe** [comment]
Rerun finished, new error message:
```
  Passed Test_StringConvertStringToVisibilityWithNegateTrue [< 1 ms]
The active test run was aborted. Reason: Unable to communicate with test host process.
Terminating app with process ID '24328'.
Results File: C:\a\Windows\Windows\TestResults\WinAppSdk.trx

The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred: 
ColorPickerExperiment.Tests.ExampleColorPickerTestClass.SimpleAsyncExampleTest

This test may, or may not be the source of the crash.
```

**Review by michael-hawker — APPROVED** [review]
LGTM, just reset the tooling pointer now that 191 is in the submodule

**Pull request merged**
